name: Publish JSR

on:
  push:
    branches: [main]
    paths:
      - "packages/*/deno.json"

permissions:
  contents: read
  id-token: write

concurrency:
  group: jsr-publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish Workspace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Publish
        run: npx jsr publish
